name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    # - name: Remove File
    #   run: find ./ -iname .sonar_lock ; rm -rf Techdome-frontend/.scannerwork/.sonar_lock
    - uses: actions/checkout@v3
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        # projectKey: "Techdome-frontend"
        args: >
          -Dsonar.projectKey=Techdome-frontend
      
    # - uses: kitabisa/sonarqube-action@master
    #   with:
    #     host: ${{ secrets.SONAR_HOST_URL }}
    #     login: ${{ secrets.SONAR_TOKEN }}
    #     #projectBaseDir: "src"
    #     projectKey: "Techdome-frontend"
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag murali90102/techdome-frontend:$GITHUB_RUN_NUMBER
    - name: Docker login 
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PWD }}
    - name: Docker push
      run: docker push murali90102/techdome-frontend:$GITHUB_RUN_NUMBER
    

  deployment:
    runs-on: self-hosted
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Picking the latest version of docker image
      run: sed -i "s/techdome-frontend:1/techdome-frontend:$GITHUB_RUN_NUMBER/1" k8_deployment/techdome-frontend.yaml
    - name: Generate config file
      run: echo "${{ secrets.KUBECTL_CONFIG }}" > config
    - name: Deployments in K8s
      run: kubectl --kubeconfig=config apply -f k8_deployment/techdome-frontend.yaml